
SELECT EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL
FROM EMPLOYEEC
WHERE EMP_LNAME LIKE 'SMITH%'
ORDER BY EMP_NUM 


--Question 2
SELECT PROJ_NAME,CAST(PROJ_VALUE AS DECIMAL(11,2)) AS PROJ_VALUE, CAST(ROUND(PROJ_BALANCE,1) AS DECIMAL(11,2)) AS PROJ_BALANCE,EMP_LNAME,EMP_FNAME,EMP_INITIAL,J.JOB_CODE,JOB_DESCRIPTION,JOB_CHG_HOUR
FROM JOB AS J INNER JOIN EMPLOYEEC AS E ON J.JOB_CODE = E.JOB_CODE
	  INNER JOIN PROJECT AS P ON E.EMP_NUM = P.EMP_NUM
ORDER BY PROJ_VALUE ASC

--Question 3
SELECT PROJ_NAME,CAST(PROJ_VALUE AS DECIMAL(11,2)) AS PROJ_VALUE, CAST(ROUND(PROJ_BALANCE,1) AS DECIMAL(11,2)) AS PROJ_BALANCE,EMP_LNAME,EMP_FNAME,EMP_INITIAL,J.JOB_CODE,JOB_DESCRIPTION,JOB_CHG_HOUR
FROM JOB AS J INNER JOIN EMPLOYEEC AS E ON J.JOB_CODE = E.JOB_CODE
	  INNER JOIN PROJECT AS P ON E.EMP_NUM = P.EMP_NUM
ORDER BY EMP_LNAME ASC

-- Question 4

SELECT DISTINCT PROJ_NUM
FROM ASSIGNMENT AS A
ORDER BY PROJ_NUM 

--QUESTION 5
SELECT ASSIGN_NUM, EMP_NUM, PROJ_NUM, ASSIGN_CHARGE, ASSIGN_CHG_HR*ASSIGN_HOURS 'CALCULATED_ASSIGN_CHG'
FROM ASSIGNMENT
ORDER BY ASSIGN_NUM ASC

--QUESTION 6
SELECT A.EMP_NUM,EMP_LNAME,SUM(ROUND(ASSIGN_HOURS,1)) AS SUMOFASSIGN_HOURS, SUM(ROUND(ASSIGN_CHARGE,1)) AS SUMOFASSIGN_CHARGE
FROM ASSIGNMENT AS A INNER JOIN EMPLOYEEC AS E ON A.EMP_NUM = E.EMP_NUM
GROUP BY A.EMP_NUM, EMP_LNAME

 -- QUESTION 7
SELECT PROJ_NUM,SUM(ROUND(ASSIGN_HOURS,1)) AS SumOfASSIGN_HOURS,SUM(ROUND(ASSIGN_CHARGE,2)) AS SumOfASSIGN_CHARGE
FROM ASSIGNMENT
GROUP BY PROJ_NUM
ORDER BY PROJ_NUM 

--QUESTION 8
SELECT SUM(ROUND(ASSIGN_HOURS,1)) AS SumofSumofASSIGN_HOURS, SUM(ROUND(ASSIGN_CHARGE,2)) AS SumofSumofASSIGN_CHARGE
FROM ASSIGNMENT AS A INNER JOIN EMPLOYEEC AS E ON A.EMP_NUM = E.EMP_NUM



