-- QUESTION 27
SELECT TOP 8 *
FROM lgdepartment
ORDER BY dept_name ASC

--QUESTION 28
SELECT PROD_SKU, PROD_DESCRIPT,PROD_TYPE, PROD_BASE, PROD_CATEGORY,PROD_PRICE
FROM lgproduct
WHERE PROD_BASE LIKE 'WATER' AND prod_category LIKE 'SEALER'

--QUESTION 29
SELECT EMP_FNAME, EMP_LNAME, EMP_EMAIL
FROM LGEMPLOYEE
WHERE EMP_HIREDATE BETWEEN '2005-01-01' AND '2014-12-31'
ORDER BY EMP_LNAME,EMP_FNAME

--QUESTION 30
SELECT EMP_FNAME, EMP_LNAME, EMP_PHONE, EMP_TITLE, DEPT_NUM
FROM lgemployee 
WHERE DEPT_NUM ='300' OR EMP_TITLE = 'CLERK I'
ORDER BY EMP_LNAME, EMP_FNAME

--QUESTION 31
SELECT LE.EMP_NUM,EMP_FNAME, EMP_LNAME,SAL_FROM, SAL_END,SAL_AMOUNT
FROM LGEMPLOYEE AS LE INNER JOIN LGSALARY_HISTORY AS LSH ON LE.EMP_NUM = LSH.EMP_NUM
WHERE LE.EMP_NUM IN (83731,83745,84039) 
ORDER BY EMP_NUM,SAL_FROM

--QUESTION 32
SELECT DISTINCT CUST_FNAME, CUST_LNAME,CUST_STREET,CUST_CITY,CUST_STATE,CUST_ZIP
FROM LGCUSTOMER AS LC  INNER JOIN LGINVOICE AS LI ON LC.CUST_CODE = LI.CUST_CODE 
	INNER JOIN LGLINE AS LL ON LI.INV_NUM = LL.INV_NUM
	INNER JOIN LGPRODUCT AS LP ON LL.PROD_SKU =LP.PROD_SKU
	INNER JOIN LGBRAND AS LB ON LP.BRAND_ID= LB.BRAND_ID
WHERE LI.INV_DATE BETWEEN '2015-07-15' AND '2015-07-31' AND BRAND_NAME = 'FORESTERS BEST' AND PROD_CATEGORY = 'TOP COAT'
ORDER BY CUST_STATE, CUST_LNAME, CUST_FNAME

--QUESTION 33
SELECT LGEMPLOYEE.EMP_NUM, EMP_LNAME, EMP_EMAIL, EMP_TITLE, DEPT_NAME
FROM LGEMPLOYEE, LGDEPARTMENT 
WHERE LGEMPLOYEE.DEPT_NUM = LGDEPARTMENT.DEPT_NUM
AND EMP_TITLE LIKE '%ASSOCIATE'
ORDER BY DEPT_NAME, EMP_TITLE

--QUESTION 34
SELECT BRAND_NAME, count(PROD_SKU) AS NUMPRODUCTS
FROM LGBRAND, LGPRODUCT
WHERE LGBRAND.BRAND_ID=LGPRODUCT.BRAND_ID  
GROUP BY BRAND_NAME 
ORDER BY BRAND_NAME

--QUESTION 35
SELECT PROD_CATEGORY, COUNT(PROD_SKU) AS NUMPRODUCTS
FROM LGPRODUCT
WHERE PROD_BASE ='WATER'
GROUP BY PROD_CATEGORY
ORDER BY PROD_CATEGORY

--QUESTION 36
SELECT PROD_BASE,PROD_TYPE, COUNT(PROD_SKU) AS NUMPRODUCTS
FROM LGPRODUCT
GROUP BY PROD_BASE,PROD_TYPE
ORDER BY PROD_BASE,PROD_TYPE

--QUESTION 37
SELECT LB.BRAND_ID, SUM(PROD_QOH) AS TOTALINVENTORY
FROM LGBRAND AS LB INNER JOIN LGPRODUCT AS LP ON LB.BRAND_ID = LP.BRAND_ID
GROUP BY LB.BRAND_ID 
ORDER BY LB.BRAND_ID DESC

--QUESTION 38 *
SELECT LB.BRAND_ID, BRAND_NAME, ROUND(AVG(CAST(PROD_PRICE AS FLOAT)), 2) AS AVGPRICE
FROM LGBRAND AS LB INNER JOIN LGPRODUCT AS LP ON LB.BRAND_ID = LP.BRAND_ID
GROUP BY LB.BRAND_ID, BRAND_NAME
ORDER BY BRAND_NAME


--QUESTION 39  *
SELECT *
FROM LGEMPLOYEE
ORDER BY DEPT_NUM
SELECT DEPT_NUM, MAX(EMP_HIREDATE) AS MOSTRECENT
FROM LGEMPLOYEE
GROUP BY DEPT_NUM
ORDER BY DEPT_NUM

--QUESTION 40 *
SELECT LE.EMP_NUM, EMP_FNAME, EMP_LNAME, MAX(CAST(SAL_AMOUNT AS FLOAT)) AS LARGESTSALARY
FROM LGEMPLOYEE AS LE, LGSALARY_HISTORY AS LS
WHERE LE.EMP_NUM = LS.EMP_NUM AND DEPT_NUM = 200
GROUP BY LE.EMP_NUM, EMP_FNAME, EMP_LNAME
ORDER BY MAX(SAL_AMOUNT) DESC

--QUESTION 41 *
SELECT *
FROM LGINVOICE
ORDER BY CUST_CODE
SELECT LGCUSTOMER.CUST_CODE,CUST_FNAME,CUST_LNAME,SUM(INV_TOTAL) AS TOTALINVOICES 
FROM LGCUSTOMER JOIN LGINVOICE ON LGCUSTOMER.CUST_CODE = LGINVOICE.CUST_CODE
GROUP BY LGCUSTOMER.CUST_CODE, CUST_FNAME,CUST_LNAME
HAVING SUM(INV_TOTAL) >1500 
ORDER BY SUM(INV_TOTAL) DESC

--QUESTION 42
SELECT LD.DEPT_NUM, DEPT_NAME, DEPT_PHONE, LD.EMP_NUM, EMP_LNAME
FROM LGDEPARTMENT AS LD INNER JOIN LGEMPLOYEE AS LE  ON LD.EMP_NUM = LE.EMP_NUM
ORDER BY DEPT_NAME

--QUESTION 43 *
SELECT LS.VEND_ID, VEND_NAME, BRAND_NAME, COUNT(LP.PROD_SKU) AS NUMPRODUCTS
FROM LGBRAND AS LB INNER JOIN LGPRODUCT AS LP ON LB.BRAND_ID = LP.BRAND_ID
	INNER JOIN LGSUPPLIES AS LS ON LP.PROD_SKU = LS.PROD_SKU
	INNER JOIN LGVENDOR AS LV ON LS.VEND_ID = LV.VEND_ID
GROUP BY LS.VEND_ID,BRAND_NAME, VEND_NAME 
ORDER BY VEND_NAME, BRAND_NAME

--QUESTION 44
SELECT EMP_NUM, EMP_LNAME, EMP_FNAME, SUM(INV_TOTAL) AS TOTALINVOICES
FROM LGINVOICE AS LI INNER JOIN LGEMPLOYEE AS LE ON EMP_NUM = EMPLOYEE_ID
GROUP BY EMP_NUM, EMP_LNAME, EMP_FNAME
ORDER BY EMP_LNAME, EMP_FNAME

--QUESTION 45 

SELECT MAX(AVGPRICE) AS 'LARGEST AVERAGE' 
FROM (SELECT P.BRAND_ID,AVG(P.PROD_PRICE) AS AVGPRICE 
FROM LGPRODUCT P
GROUP BY BRAND_ID) AS AVGPRICE

--QUESTION 46 *
SELECT B.BRAND_ID, BRAND_NAME, BRAND_TYPE, AVG(PROD_PRICE) AS AVGPRICE
FROM LGBRAND B INNER JOIN LGPRODUCT P ON B.BRAND_ID = P.BRAND_ID 
GROUP BY B.BRAND_ID, BRAND_NAME, BRAND_TYPE
HAVING AVG(PROD_PRICE) = (SELECT MAX(AVGPRICE) FROM (SELECT BRAND_ID, AVG(PROD_PRICE) AS 'AVGPRICE' FROM LGPRODUCT GROUP BY BRAND_ID)A)

--QUESTION 47
SELECT [MANAGER FNAME], [MANAGER LNAME],MAN.DEPT_NAME, MAN.DEPT_PHONE, EMP_FNAME, EMP_LNAME, CUST_FNAME, CUST_LNAME, INV_DATE, INV_TOTAL
FROM (
SELECT D.DEPT_NUM,DEPT_NAME, DEPT_PHONE, E.EMP_NUM, EMP_LNAME AS [MANAGER LNAME], EMP_FNAME AS[MANAGER FNAME]
FROM LGEMPLOYEE E INNER JOIN LGDEPARTMENT D ON E.EMP_NUM = D.EMP_NUM
GROUP BY  D.DEPT_NUM,DEPT_NAME, DEPT_PHONE, E.EMP_NUM, EMP_LNAME, EMP_FNAME)MAN INNER JOIN
(SELECT DEPT_NAME, DEPT_PHONE, EMP_FNAME, EMP_LNAME, CUST_FNAME, CUST_LNAME, INV_DATE, INV_TOTAL
FROM LGCUSTOMER C INNER JOIN LGINVOICE I ON C.CUST_CODE = I.CUST_CODE
	INNER JOIN LGEMPLOYEE E ON I.EMPLOYEE_ID = E.EMP_NUM
	INNER JOIN LGDEPARTMENT D ON E.DEPT_NUM = D.DEPT_NUM
WHERE CUST_LNAME = 'HAGAN' AND INV_DATE = '2015-05-18') EMP ON MAN.DEPT_NAME = EMP.DEPT_NAME


--QUESTION 48 
SELECT LE.EMP_NUM, EMP_LNAME, EMP_FNAME, CAST(SAL_AMOUNT AS FLOAT)
FROM LGEMPLOYEE AS LE JOIN LGSALARY_HISTORY AS LS ON LE.EMP_NUM = LS.EMP_NUM
WHERE SAL_END IS NULL AND DEPT_NUM = 300
ORDER BY SAL_AMOUNT DESC


--QUESTION 49 
SELECT EMP.EMP_NUM, EMP.EMP_LNAME, EMP.EMP_FNAME, CAST(SAL.SAL_AMOUNT AS FLOAT)
 FROM LGEMPLOYEE EMP JOIN LGSALARY_HISTORY SAL ON EMP.EMP_NUM = SAL.EMP_NUM
WHERE SAL.SAL_FROM =
       (SELECT MIN(SAL2.SAL_FROM) 
	   FROM LGSALARY_HISTORY SAL2 WHERE EMP.EMP_NUM = SAL2.EMP_NUM)
ORDER BY EMP.EMP_NUM

--QUESTION 50
SELECT L.INV_NUM, L.LINE_NUM, P.PROD_SKU, P.PROD_DESCRIPT, L2.LINE_NUM, P2.PROD_SKU,P2.PROD_DESCRIPT, P.BRAND_ID
FROM (LGLINE L JOIN LGPRODUCT P ON L.PROD_SKU = P.PROD_SKU) JOIN (LGLINE L2 JOIN LGPRODUCT P2 ON L2.PROD_SKU = P2.PROD_SKU) ON L.INV_NUM = L2.INV_NUM
WHERE P.BRAND_ID = P2.BRAND_ID AND P.PROD_CATEGORY = 'SEALER 'AND P2.PROD_CATEGORY = 'TOP COAT'
ORDER BY L.INV_NUM ASC, L.LINE_NUM ASC,L2.LINE_NUM DESC

--QUUESTION 51
SELECT *
FROM(SELECT EMP_NUM, EMP_FNAME, EMP_LNAME, EMP_EMAIL ,SUM(L.LINE_QTY) AS TOTAL
FROM LGEMPLOYEE E INNER JOIN  LGINVOICE I ON E.EMP_NUM = I.EMPLOYEE_ID
INNER JOIN lGLINE L ON I.INV_NUM = L.INV_NUM 
INNER JOIN LGPRODUCT P ON L.PROD_SKU = P.PROD_SKU
INNER JOIN LGBRAND B ON P.BRAND_ID = B.BRAND_ID 
WHERE BRAND_NAME = 'BINDER PRIME' AND INV_DATE BETWEEN '2015/11/01' AND '2015/12/05'
GROUP BY  EMP_NUM, EMP_FNAME, EMP_LNAME, EMP_EMAIL) T
WHERE TOTAL =(SELECT MAX(TOTAL) FROM (SELECT EMP_NUM, EMP_FNAME, EMP_LNAME, EMP_EMAIL ,SUM(L.LINE_QTY) AS TOTAL
FROM LGEMPLOYEE E INNER JOIN  LGINVOICE I ON E.EMP_NUM = I.EMPLOYEE_ID
INNER JOIN lGLINE L ON I.INV_NUM = L.INV_NUM 
INNER JOIN LGPRODUCT P ON L.PROD_SKU = P.PROD_SKU
INNER JOIN LGBRAND B ON P.BRAND_ID = B.BRAND_ID 
WHERE BRAND_NAME = 'BINDER PRIME' AND INV_DATE BETWEEN '2015/11/01' AND '2015/12/05'
GROUP BY  EMP_NUM, EMP_FNAME, EMP_LNAME, EMP_EMAIL)S)
ORDER BY EMP_LNAME


--QUESTION 52
SELECT LC.CUST_CODE, CUST_FNAME, CUST_LNAME
FROM LGCUSTOMER AS LC JOIN LGINVOICE AS LI ON LC.CUST_CODE=LI.CUST_CODE
WHERE EMPLOYEE_ID = 83649
INTERSECT
SELECT LC.CUST_CODE, CUST_FNAME, CUST_LNAME
FROM LGCUSTOMER AS LC JOIN LGINVOICE AS LI ON LC.CUST_CODE=LI.CUST_CODE
WHERE EMPLOYEE_ID = 83677
ORDER BY CUST_LNAME, CUST_FNAME;


--QUESTION 53 
SELECT C.CUST_CODE, C.CUST_FNAME, CUST_LNAME, CUST_STREET, CUST_CITY, CUST_STATE, CUST_ZIP, INV_DATE, INV_TOTAL AS LARGESTINVOICE
FROM LGCUSTOMER AS C INNER JOIN LGINVOICE AS I ON C.CUST_CODE = I.CUST_CODE
WHERE CUST_STATE= 'AL' AND INV_TOTAL= (SELECT MAX(INV_TOTAL) FROM LGINVOICE I WHERE I.CUST_CODE=C.CUST_CODE)

UNION 

SELECT CUST_CODE, CUST_FNAME, CUST_LNAME, CUST_STREET, CUST_CITY, CUST_STATE, CUST_ZIP, NULL,0 
FROM LGCUSTOMER
WHERE  CUST_STATE= 'AL' AND CUST_CODE NOT IN (SELECT CUST_CODE FROM LGINVOICE)
ORDER BY CUST_LNAME, CUST_FNAME









